### ISSUE TITLE
[Bot/Record/Create/Message] Add Markdown style formatting to Messages created by Bot / API

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1242]
This Feature-Request aims to profit of the "markdown" syntax while creating new messages trough a Bot.

If you create a ticket and a saved message trough the API, you'd use [ticket/compose](https://cerb.ai/docs/api/endpoints/tickets/) with the option **dont_send** instead. There cou can choose a **content_format**. Also [comments](https://cerb.ai/docs/records/types/comment/) let you choose a format while creating them by a Bot or the API. This _format_ option seems missing or not documented for messages created trough Bots / API.

**Comment by jstanden** [comment]
In 10.0+ with automations you can create a compose, reply, or transactional message by starting with a draft:
https://cerb.ai/docs/records/types/draft/#params-mailtransactional

That has access to all of the options. You'd just schedule it for the current time (`queue_delivery_date@date: now`) and set `is_queued=1`.

10.1 includes an auto-reply example, like:

```yaml
start:
  # Don't send auto-replies to automated senders
  outcome/isAutoSender:
    if@bool:
      {{
        message_sender_email is prefixed ('postmaster@','mailer-daemon@')
        or message_headers['auto-submitted'] is prefixed ('auto-')
        or message_headers['precedence'] == 'bulk'
        or message_headers['preference'] == 'auto_reply'
        or message_headers['x-precedence']
        or message_headers['x-autorespond']
        or message_headers['x-autogenerated']
        or message_headers['x-autoreply-from']
        or 'autoreply' in message_headers['x-auto-response-suppress']|lower
        or 'out of office' in message_headers['subject']|lower
        or 'out of the office' in message_headers['subject']|lower
      }}    
    then:
      return:
  
  # See: https://cerb.ai/docs/automations/commands/record.create/
  record.create/draft:
    output: new_draft
    inputs:
      record_type: draft
      # See: https://cerb.ai/docs/records/types/draft/#records-api
      fields:
        type: mail.transactional
        name: Auto-reply to {{message_sender_email}}
        to: {{message_sender_email}}
        is_queued: 1
        queue_delivery_date@date: now
        params:
          to: {{message_sender_email}}
          from: support@cerb.example
          subject: Auto-Reply: {{message_ticket_subject}}
          headers:
            Auto-Submitted: auto-replied
            Precedence: bulk
          content@text:
            Thanks for writing!
            
            Your reference number is #{{message_ticket_mask}}.
```
