### ISSUE TITLE
[Sheets/Markdown] Sheet 'markdown' column type

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#1560]
This would complement the `text` column type, but allow Markdown formatting (HTML disabled).

**Comment by jstanden** [comment]
This isn't necessary now. You can use Markdown in sheets like:

```yaml
text/message:
  params:
      value_template@raw: {{message|markdown_to_html(is_untrusted=true)|raw}}
```
