### ISSUE TITLE
[Automation/Autocomplete] Add inputs of called interaction

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1729]
In automations of type _cerb.trigger.interaction.worker_, when using a form with _data from automation_, the input-parameter from the automation called (green) are available in the "parent"-automation and show up as autocomplete-suggestion

This autocompletes "seems" missing when we call an _interaction_ (red). This is no blocker, but may affect usability.

![image](https://github.com/jstanden/cerb/assets/17173365/0846a57d-867b-4e2c-a9f0-6b09fe6209d2)

Reproduced in 10.3.10, didn't find a remark about this for 10.4

**Comment by jstanden** [comment]
Hi Beat!

Great catch. I'll implement the autocompletion suggestions for `await:interaction:inputs:` too.

Also, keep in mind that the interaction will run one action per `await:`.

So rather than:

```yaml
start:
  await:
    form: ...
    interaction: ...
```

Do:

```yaml
start:
  await/someName:
    form:
      title: Form Title
      elements: ...
  
  await/someOtherName:
    interaction:
      uri: cerb:automation:wgm.interaction.dnsLookup
      inputs: ...
```

That will give you two subsequent `await:` branches.
