### ISSUE TITLE
[Packages/Widgets/Charts] Tickets per quarter

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#1805]
This should be added to the workspace widget library:

```yaml
{
    "widget": {
        "uid": "workspace_widget_tickets_per_quarter",
        "_context": "cerberusweb.contexts.workspace.widget",
        "label": "Tickets per quarter",
        "extension_id": "cerb.workspace.widget.chart.kata",
        "pos": 1,
        "width_units": 4,
        "zone": "content",
        "params": {
            "datasets_kata": "dataQuery/series0:\r\n  query@text:\r\n    type:worklist.subtotals\r\n    of:ticket\r\n    by.count:[created@quarter~20]\r\n    query:(created:\"today -3 years to now\")\r\n    format:categories",
            "placeholder_simulator_kata": "",
            "chart_kata": "data:\r\n  series:\r\n    series0:\r\n      x_key: label\r\n\r\naxis:\r\n  x:\r\n    type: category\r\n    categories@csv:\r\n      {{date_lerp(\"today -3 years to now\",\"quarter\",1)|map((ts) => ts|date('Y-\\Q') ~ (ts|date('m')/3))|join(',')}}\r\n    tick:\r\n      fit@bool: no\r\n      multiline@bool: no\r\n      rotate: -90"
        }
    }
}
```
